baseURL = "https://runrunicd.github.io/blog/" 
languageCode = "en-us"
title = "Shel (Run) Zhou's Blog"
theme = "PaperMod"

enableInlineShortcodes = true
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true
#googleAnalytics = "UA-123-45"

[params]
  env = "production" # to enable google analytics, opengraph, twitter-cards and schema.
  description = ""
  author = "Run Zhou"
  # author = ["Me", "You"] # multiple authors
  
  defaultTheme = "auto"
  # disableThemeToggle = true
  ShowShareButtons = true
  ShowReadingTime = true
  # disableSpecial1stPost = true
  displayFullLangName = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowRssButtonInSectionTermList = true
  ShowToc = true
  # comments = false

  [params.homeInfoParams]
    Title = "Hi, Shel's here. Who's there?"
    Content = " This is my learning hub. I learn new things through reading, building, and thinking. In my leisure time, I love ğŸ¾, ğŸƒâ€â™€ï¸, ğŸ“», ğŸ“–, ğŸ¨, âœˆï¸, ğŸ¶."

  [[params.socialIcons]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/runz/"

  [[params.socialIcons]]
    name = "Github"
    url = "https://github.com/runrunicd"

[menu]
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
    weight = 30

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 40

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/post/"
    weight = 10

  [[menu.main]]
    identifier = "books"
    name = "Books"
    url = "/books/"
    weight = 50

[minify]
disableXML = true
# minifyOutput = true

[outputs]
home = ["HTML", "RSS", "JSON"]


[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false

[privacy]

  [privacy.vimeo]
  disabled = false
  simple = true

[services]

  [services.instagram]
  disableInlineCSS = true

  [services.twitter]
  disableInlineCSS = true





